language: ruby
rvm:
  - 2.4.2
services:
  - postgresql
env:
  - RAILS_ENV=test
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - bundle exec rake db:schema:load
  - bundle exec rake db:test:prepare
  - bundle exec rspec
